version: "3.5"
# You should be able to find & replace all instances of gocd with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  gocd:
  gocd-private:

volumes:
  gocd:
  gocd-db:

secrets:
  # Secrets format
  # ${service_name}_${mount_point}:
  #   name: ${STACK_NAME:-technocore}_${service_name}_${mount_point}
  # #   external: true
  gocd_admin_username:
    name: ${STACK_NAME:-technocore}_gocd_admin_username
    external: true
  gocd_admin_password:
    name: ${STACK_NAME:-technocore}_gocd_admin_password
    external: true
  gocd_gocd-db_username:
    name: ${STACK_NAME:-technocore}_gocd_gocd-db_username
    external: true
  gocd_gocd-db_password:
    name: ${STACK_NAME:-technocore}_gocd_gocd-db_password
    external: true

services:
  ## Uncomment this if Traefik will be used for routing traffick to this service.
  #ingress:
  #  networks:
  #    - gocd

  gocd:
    deploy:
      labels:
      #  - traefik.frontend.rule=$GOCD_ROUTING_LABEL
      #  - traefik.frontend.priority=$GOCD_ROUTING_LABEL_PRIORITY
      #  - traefik.port=SET_ME_PLEASE
      #  - ${TRAEFIK_BASIC_AUTH}
      #  - traefik.enable=true
      #  # You'll need to set applicaiton's port here.
      #  - traefik.tags=ingress 
      #  - traefik.docker.network=${STACK_NAME:-technocore}_gocd
      #  # Traefik service that listens to HTTP
      #  - traefik.redirectorservice.frontend.entryPoints=http
      #  - traefik.redirectorservice.frontend.redirect.entryPoint=https
      #  # Traefik service that listens to HTTPS
      #  - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - ADMIN_USER=${ADMIN_USER}
    image: ${image_provider:-scififarms}/technocore-gocd:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - gocd
      - gocd-private
    #secrets:
    #  - source: gocd_gocd_db_password
    #    target: gocd_db_password
    volumes:
      # Likely need to change this
      - gocd:/var/lib/gocd
      # This should in fact be all upper case.
      - ${DEV_MOUNT_gocd_SHELL_MIGRATIONS:-$EMPTY_MOUNT}

  gocd_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    #environment:
    image: ${image_provider:-scififarms}/technocore-gocd-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - gocd-private
    secrets:
      - source: gocd_db_admin_username
        target: admin_username
      - source: gocd_db_admin_password
        target: admin_password
      - source: gocd_db_gocd_username
        target: gocd_username
      - source: gocd_db_gocd_password
        target: gocd_password
    volumes:
      # Likely need to change this
      - gocd-db:/var/lib/gocd
